version: '3.4'
services:
  #Nginx Service
  Figaro-1 :
    image: nginx:alpine
    container_name: figaro1
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=figaro"
      - "traefik.frontend.rule=Host:figaro.localhost"
      - "traefik.port=80"      
    volumes:
      - ./indexF1.html:/usr/share/nginx/html/index.html
  
  Figaro-2 :
    image: nginx:alpine
    container_name: figaro2
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=figaro"
      - "traefik.frontend.rule=Host:figaro.localhost"
      - "traefik.port=80"      
    volumes:
      - ./indexF2.html:/usr/share/nginx/html/index.html

  Gorafi-1 :
    image: nginx:alpine
    container_name: gorafi1
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=gorafi"
      - "traefik.frontend.rule=Host:gorafi.localhost"
      - "traefik.port=80"     
    volumes:
      - ./indexG1.html:/usr/share/nginx/html/index.html
  
  Gorafi-2 :
    image: nginx:alpine
    container_name: gorafi2
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=gorafi"
      - "traefik.frontend.rule=Host:gorafi.localhost"
      - "traefik.port=80"    
    volumes:
      - ./indexG2.html:/usr/share/nginx/html/index.html

#Docker Networks
networks: 
  app-network:
    driver: bridge
  traefik:
    external: 
      name: traefik_webgateway   
